export default Message;
export type ValidateFn = (value: any) => boolean | Error | Error[] | Record<string, boolean | Error[]>;
export type MessageInput = import("./Message.js").MessageInput;
import App from "./App.js";
import Chat from "./Chat.js";
import Contact from "./Contact.js";
import Language from "./Language.js";
import Message from "./Message.js";
import InputMessage from "./InputMessage.js";
import OutputMessage from "./OutputMessage.js";
import I18nMessage from "./I18nMessage.js";
export { App, Chat, Contact, Language, Message, InputMessage, OutputMessage, I18nMessage };
